Controllers/InmuebleController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Inmobiliaria_Cerutti.Models;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Authorization;
using MySql.Data.MySqlClient;

namespace Inmobiliaria_Cerutti.InmuebleController;

[Authorize]
public class InmuebleController : Controller
{
    private readonly ILogger<InmuebleController> _logger;

    public InmuebleController(ILogger<InmuebleController> logger)
    {
        _logger = logger;
    }



    public IActionResult Index()
    {
        var rinmuble = new RepositorioInmueble();
        var lista = rinmuble.GetInmuebles();
        return View(lista);
    }

    public IActionResult Crear()//formulario de alta
    {
        try
        {
            var rp = new RepositorioPropietario();
            ViewBag.Propietarios = rp.GetPropietarios();//obtengo los propietario y se los paso a la vista
            
            var rt = new RepositorioTipoInmueble();
            ViewBag.TipoInmuebles = rt.GetTipoInmuebles();
            return View();
        }
        catch (Exception ex)
        {
            // Devuelve una vista de error genérica
            ViewBag.ErrorMessage = ex.Message;
            return View("Error");
        }
    }

    [HttpPost]
    public IActionResult Guardar(Inmueble inmueble)
{
    try
    {
        var ri = new RepositorioInmueble();
        ri.AltaInmueble(inmueble);
        TempData["mensaje"] = "Inmueble guardado con éxito!";
        return RedirectToAction(nameof(Index));
    }
    catch (MySqlException ex) when (ex.Number == 1062)
    {
        // Error de duplicado
        TempData["error"] = "Error: Ya existe un Inmueble en esa dirección.";
        return RedirectToAction(nameof(Crear));
    }
    catch (Exception ex)
    {
        // Otros errores
        TempData["error"] = "Error: Debe seleccionar tipo de inmueble.";
        return RedirectToAction(nameof(Crear));
    }
}


    [Authorize(Roles = "Administrador")]
    public IActionResult Eliminar(int id)
    {
        try
        {
            var ri = new RepositorioInmueble();
            ri.eliminarPropiedad(id);
            TempData["mensaje"] = "Inmueble Eliminado con exito!";
            return RedirectToAction(nameof(Index));
        }
        catch (Exception ex)
        {
            TempData["error"] = "Error: al eliminar el inmueble.";
            return RedirectToAction(nameof(Index));
        }


    }

    // GET: Inmueble/
    public ActionResult Editar(int id)
    {
        var ri = new RepositorioInmueble();
        var inmueble = ri.GetInmueble(id);
        var rp = new RepositorioPropietario();
        ViewBag.Propietarios = rp.GetPropietarios();
        var rt = new RepositorioTipoInmueble();
        ViewBag.TipoInmuebles = rt.GetTipoInmuebles();
        return View(inmueble);
    }
    // POST: Inmueble/Edit/
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Editar(int id, Inmueble inmueble)
    {
        try
        {
            var ri = new RepositorioInmueble();
            var rp = new RepositorioPropietario();
            
            inmueble.id_inmueble = id;
            ri.EditarInmueble(inmueble);
            TempData["Mensaje"] = "Inmueble editado correctamente";
            return RedirectToAction(nameof(Index));
        }
        catch (Exception ex)
        {
            var rp = new RepositorioPropietario();
            ViewBag.Propietarios = rp.GetPropietarios();
            ViewBag.Error = ex.Message;
            TempData["Error"] = "Error al editar el Inmueble";
            return View(inmueble);
        }
    }
}

Controllers/PagoController.cs
using Inmobiliaria_Cerutti.UsuarioController;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using Org.BouncyCastle.Asn1.Iana;
namespace Inmobiliaria_Cerutti.PagoController;

[Authorize]
public class PagoController : Controller
{
    private readonly ILogger<PagoController> _logger;

    public PagoController(ILogger<PagoController> logger)
    {
        _logger = logger;
    }


    public IActionResult Index()
    {
        var rpago = new RepositorioPago();
        var pagos = rpago.GetPagos();
        return View(pagos);
    }
    public IActionResult buscar()
    {
        return View();
    }
    public IActionResult buscarDni(string dni)
    {
        var rc = new RepositorioContrato();
        var contratos = rc.GetContratoPorDni(dni);

        if (contratos != null && contratos.Any()) // Verificamos si la lista tiene elementos
        {
            ViewBag.Contratos = contratos; // Pasamos los contratos a la vista usando ViewBag
            return View("Pagar");
        }else if(dni == null){
            TempData["Error"] = "Error: Ingrese un Dni!";
            return View("buscar");
        }
        else
        {
            TempData["Error"] = "Error: No hay contratos registrados";
            return View("buscar");
        }
        
    }

 public IActionResult buscarEmail(string email)
    {
        var rc = new RepositorioContrato();
        var contratos = rc.GetContratoPorEmail(email);

        if (contratos != null && contratos.Any()) // Verificamos si la lista tiene elementos
        {
            ViewBag.Contratos = contratos; // Pasamos los contratos a la vista usando ViewBag
            return View("Pagar");
        }else if(email == null){
            TempData["Error"] = "Error: Ingrese un Email!";
            return View("buscar");
        }
        else
        {
            TempData["Error"] = "Error: No hay contratos registrados";
            return View("buscar");
        }
    }


    public IActionResult Pagar(int id_contrato)
    {
        ViewBag.IdContrato = id_contrato;
        return View();
    }



    [HttpPost]
    public IActionResult Pagar(Pago pago)
    {

        var rpago = new RepositorioPago();
        try
        {
            rpago.Pagar(pago);
            TempData["mensaje"] = "Pago realizado con éxito.";
            return RedirectToAction("Index");
        }
        catch (MySqlException ex)
        {
            TempData["error"] = $"Error al realizar el pago: {ex.Message}";
            return View(pago);
        }

    }

    [Authorize(Roles = "Administrador")]
    public IActionResult Eliminar(int id)
    {
        var rpago = new RepositorioPago();
        try
        {
            rpago.EliminarPago(id);
            TempData["mensaje"] = "Pago eliminado con éxito.";
            return RedirectToAction(nameof(Index));
        }
        catch (Exception ex)
        {
            TempData["error"] = $"Error al eliminar el pago: {ex.Message}";
            return RedirectToAction(nameof(Index));
        }

    }

public IActionResult Editar(int id)
{
    var rpago = new RepositorioPago();
    try
    {
        var pago = rpago.GetPago(id);
        if (pago == null)
        {
            TempData["error"] = "Pago no encontrado.";
            return RedirectToAction(nameof(Index));
        }
        return View(pago); // Pasa el modelo a la vista
    }
    catch (Exception ex)
    {
        TempData["error"] = $"Error al obtener el pago: {ex.Message}";
        return RedirectToAction(nameof(Index));
    }
}

[HttpPost]
public IActionResult Editar(Pago pago)
{
    try
    {
        var rpago = new RepositorioPago();
        rpago.EditarPago(pago);
        TempData["mensaje"] = "Pago Modificado!";
        return RedirectToAction(nameof(Index)); 
    }
    catch (Exception ex)
    {
        TempData["error"] = $"No se pudo editar el pago: {ex.Message}";
        return RedirectToAction(nameof(Index)); 
    }
}


}

Controllers/UsuarioController.cs
using System.Security.Cryptography;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using Microsoft.AspNetCore.Authorization;


[Authorize(Roles = "Administrador")] //que esten autorizados y sea admin
//significa que este controlador solo van a tener acceso a las rutas los admin.
public class UsuarioController : Controller
{

    public UsuarioController()
    {

    }

    public IActionResult Index()
    {
        var ru = new RepositorioUsuario();
        var usuarios = ru.GetUsuarios();
        return View(usuarios);
    }

    [HttpGet]
    public IActionResult Crear()
    {
        return View();
    }

    private static string GenerateSalt(int size = 32)
    {
        var rng = new RNGCryptoServiceProvider();
        var saltBytes = new byte[size];
        rng.GetBytes(saltBytes);
        return Convert.ToBase64String(saltBytes);
    }
    private static string HashPassword(string password, string salt)
    {
        return Convert.ToBase64String(KeyDerivation.Pbkdf2(
            password: password,
            salt: Convert.FromBase64String(salt),
            prf: KeyDerivationPrf.HMACSHA1,
            iterationCount: 1000,
            numBytesRequested: 256 / 8));
    }



    [HttpPost]
    public IActionResult Crear(Usuario usuario)
    {
        try
        {
            if (usuario.AvatarFile != null && usuario.AvatarFile.Length > 0)
            {
                // Ruta de la carpeta de avatares
                var avatarsPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "avatars");

                // Creo la carpeta avatars si no existe
                if (!Directory.Exists(avatarsPath))
                {
                    Directory.CreateDirectory(avatarsPath);
                }

                // Genero un nombre único para el archivo del avatar
                var uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(usuario.AvatarFile.FileName);

                // Ruta completa donde se guardará el archivo
                var filePath = Path.Combine(avatarsPath, uniqueFileName);

                // Guardo el archivo
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    usuario.AvatarFile.CopyTo(stream);
                }

                // Guardo la ruta del nuevo avatar en la base de datos
                usuario.AvatarUrl = "/avatars/" + uniqueFileName;
            }
            else
            {
                // Si no se selecciona un avatar, se asigna un valor por defecto o vacío
                usuario.AvatarUrl = "";
            }

            // Generar Salt y hashear la contraseña
            usuario.Salt = GenerateSalt();
            usuario.Clave = HashPassword(usuario.Clave, usuario.Salt);

            var ru = new RepositorioUsuario();
            ru.CrearUsuario(usuario);
            TempData["Mensaje"] = "Usuario Creado con exito!";
            return RedirectToAction("Index");

        }
        catch (MySqlException ex) when (ex.Number == 1062)
        {
            TempData["Error"] = "Error: El usuario ya esta registrado! ";
            return View();
        }

    }


    
    public IActionResult eliminar(int id)
    {
        try
        {
            var ru = new RepositorioUsuario();
            ru.EliminarUsuario(id);
            TempData["Mensaje"] = "Usuario Eliminado con exito!";
            return RedirectToAction(nameof(Index));
        }
        catch (MySqlException ex)
        {
            TempData["error"] = "Error al eliminar el usuario.";
            return RedirectToAction(nameof(Index));
        }

    }

    [HttpGet]
    public IActionResult Editar(int id)
    {
        var ru = new RepositorioUsuario();
        var usuario = ru.GetUsuarioById(id);
        return View(usuario);
    }

    // Acción POST para actualizar el usuario admin

    [HttpPost]
   public IActionResult Editar(Usuario usuario, bool eliminarAvatar)
{
    try
    {
        var ru = new RepositorioUsuario();
        var usuarioExistente = ru.GetUsuarioById(usuario.Id);

        // Manejar el archivo del avatar si se sube uno nuevo
        if (usuario.AvatarFile != null && usuario.AvatarFile.Length > 0)
        {
            // Ruta de la carpeta de avatares
            var avatarsPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "avatars");

            // Creo la carpeta avatars si no existe
            if (!Directory.Exists(avatarsPath))
            {
                Directory.CreateDirectory(avatarsPath);
            }

            // Genero un nombre único para el archivo del avatar
            var uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(usuario.AvatarFile.FileName);

            // Ruta completa donde se guardará el archivo
            var filePath = Path.Combine(avatarsPath, uniqueFileName);

            // Guardo el archivo
            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                usuario.AvatarFile.CopyTo(stream);
            }

            // Guardo la ruta del nuevo avatar en la base de datos
            usuario.AvatarUrl = "/avatars/" + uniqueFileName;
        }
        else if (eliminarAvatar && !string.IsNullOrEmpty(usuarioExistente.AvatarUrl))
        {
            // Si se debe eliminar el avatar existente
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", usuarioExistente.AvatarUrl.TrimStart('/'));

            // Eliminar el archivo del servidor
            if (System.IO.File.Exists(filePath))
            {
                System.IO.File.Delete(filePath);
            }

            // Limpiar la URL del avatar en la base de datos
            usuario.AvatarUrl = "";
        }
        else
        {
            // Mantener el avatar existente si no se elimina ni cambia
            usuario.AvatarUrl = usuarioExistente.AvatarUrl;
        }

        // Generar Salt y hashear la contraseña si se proporciona una nueva
        if (!string.IsNullOrEmpty(usuario.Clave))
        {
            usuario.Salt = GenerateSalt();
            usuario.Clave = HashPassword(usuario.Clave, usuario.Salt);
        }
        else
        {
            // Mantener la contraseña y el salt existente si no se proporciona una nueva
            usuario.Clave = usuarioExistente.Clave;
            usuario.Salt = usuarioExistente.Salt;
        }

        ru.EditarUsuario(usuario);
        TempData["mensaje"] = "Usuario modificado con éxito!";

        return RedirectToAction("Index");
    }
    catch (MySqlException ex) when (ex.Number == 1062)
    {
        TempData["error"] = "Error: El mail elegido ya está en uso, cambie el mail.";
        return View(usuario);
    }
    catch (Exception ex)
    {
        TempData["error"] = "Error al modificar el usuario: " + ex.Message;
        return View(usuario);
    }
}


}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inmobiliaria_Cerutti</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        integrity="sha384-k6RqeWeci5ZR/Lv4MR0sA0FfDOM57QzZZa+zElN5z8gtpPftvjcPp6x5J5rErFd8" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Inmobiliaria_Cerutti.styles.css" asp-append-version="true" />
</head>

@using Microsoft.AspNetCore.Identity

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-building"></i> Inmobiliaria Cerutti
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if(User.IsInRole("Administrador")||User.IsInRole("Empleado")){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fas fa-home"></i> Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">
                                <i class="fas fa-user-secret"></i> Privacy
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inquilino" asp-action="Index">
                                <i class="fas fa-user"></i> Inquilinos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Propietario" asp-action="Index">
                                <i class="fas fa-user-tie"></i> Propietarios
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inmueble" asp-action="Index">
                                <i class="fas fa-home"></i> Inmuebles
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contrato" asp-action="Index">
                                <i class="fas fa-file-contract"></i> Contratos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pago" asp-action="Index">
                                <i class="fas fa-money-bill"></i> Pagos
                            </a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoInmueble" asp-action="Index">
                                <i class="fa-solid fa-warehouse"></i> TipoInmueble
                            </a>
                        </li>
                        }
                        @if(User.IsInRole("Administrador")){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">
                                <i class="fas fa-user-circle"></i> Usuarios
                            </a>
                        </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark user-name" href="#" id="usuarioDropdown"
                                    role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    @User.Identity.Name
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="usuarioDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Perfil">
                                        <i class="fas fa-user"></i> Perfil
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Logout">
                                        <i class="fas fa-sign-out-alt"></i> Log Out
                                    </a>
                                </div>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">
                                    <i class="fas fa-sign-in-alt"></i> Login
                                </a>
                            </li>
                        }
                    </ul>
                </div>

            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Inmobiliaria_Cerutti - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>



    @await RenderSectionAsync("Scripts", required: false)


</body>

</html>